#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
Name     : compat-codec2-soname1
Version  : 1.0.5
Release  : 26
URL      : https://github.com/drowe67/codec2/archive/v1.0.5/codec2-1.0.5.tar.gz
Source0  : https://github.com/drowe67/codec2/archive/v1.0.5/codec2-1.0.5.tar.gz
Summary  : A speech codec for 2400 bit/s and below
Group    : Development/Tools
License  : LGPL-2.1
Requires: compat-codec2-soname1-lib = %{version}-%{release}
Requires: compat-codec2-soname1-license = %{version}-%{release}
BuildRequires : LPCNet-dev
BuildRequires : buildreq-cmake
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : octave
BuildRequires : pkgconfig(samplerate)
BuildRequires : pkgconfig(speexdsp)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: fsk_fft_api.patch
Patch2: modern-cmake-targets.patch

%description
An Orthogonal Frequency Division Multiplexed (OFDM) modem designed for digital voice over HF SSB.  Typical configuration for FreeDV 700D is 700 bit/s voice, a rate 0.5 LDPC code, and 1400 bit/s raw data rate over the channel.

%package lib
Summary: lib components for the compat-codec2-soname1 package.
Group: Libraries
Requires: compat-codec2-soname1-license = %{version}-%{release}

%description lib
lib components for the compat-codec2-soname1 package.


%package license
Summary: license components for the compat-codec2-soname1 package.
Group: Default

%description license
license components for the compat-codec2-soname1 package.


%prep
%setup -q -n codec2-1.0.5
cd %{_builddir}/codec2-1.0.5
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1683298307
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx512
pushd clr-build-avx512
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -O3 -Wl,-z,x86-64-v4 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86_64-v4 -mprefer-vector-width=512 "
export FCFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v4 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86_64-v4 -mprefer-vector-width=512 "
export FFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v4 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86_64-v4 -mprefer-vector-width=512 "
export CXXFLAGS="$CXXFLAGS -O3 -Wl,-z,x86-64-v4 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86_64-v4 -mprefer-vector-width=512 "
export CFLAGS="$CFLAGS -march=x86-64-v4 -m64 -Wl,-z,x86-64-v4 -mprefer-vector-width=512"
export CXXFLAGS="$CXXFLAGS -march=x86-64-v4 -m64 -Wl,-z,x86-64-v4 -mprefer-vector-width=512"
export FFLAGS="$FFLAGS -march=x86-64-v4 -m64 -Wl,-z,x86-64-v4 -mprefer-vector-width=512"
export FCFLAGS="$FCFLAGS -march=x86-64-v4 -m64 "
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :
cd ../clr-build-avx512;
make test || : || :

%install
export SOURCE_DATE_EPOCH=1683298307
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-codec2-soname1
cp %{_builddir}/codec2-%{version}/COPYING %{buildroot}/usr/share/package-licenses/compat-codec2-soname1/af54222a16839088fb1ffd5da88c1713472babc4 || :
pushd clr-build-avx512
%make_install_v4  || :
popd
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}*/V4/usr/bin/c2dec
rm -f %{buildroot}*/V4/usr/bin/c2enc
rm -f %{buildroot}*/V4/usr/bin/fdmdv_demod
rm -f %{buildroot}*/V4/usr/bin/fdmdv_get_test_bits
rm -f %{buildroot}*/V4/usr/bin/fdmdv_mod
rm -f %{buildroot}*/V4/usr/bin/fdmdv_put_test_bits
rm -f %{buildroot}*/V4/usr/bin/fm_demod
rm -f %{buildroot}*/V4/usr/bin/fsk_mod
rm -f %{buildroot}*/V4/usr/bin/insert_errors
rm -f %{buildroot}*/V4/usr/lib64/libcodec2.so
rm -f %{buildroot}*/usr/bin/c2dec
rm -f %{buildroot}*/usr/bin/c2enc
rm -f %{buildroot}*/usr/bin/fdmdv_demod
rm -f %{buildroot}*/usr/bin/fdmdv_get_test_bits
rm -f %{buildroot}*/usr/bin/fdmdv_mod
rm -f %{buildroot}*/usr/bin/fdmdv_put_test_bits
rm -f %{buildroot}*/usr/bin/fm_demod
rm -f %{buildroot}*/usr/bin/fsk_mod
rm -f %{buildroot}*/usr/bin/insert_errors
rm -f %{buildroot}*/usr/include/codec2/codec2.h
rm -f %{buildroot}*/usr/include/codec2/codec2_cohpsk.h
rm -f %{buildroot}*/usr/include/codec2/codec2_fdmdv.h
rm -f %{buildroot}*/usr/include/codec2/codec2_fifo.h
rm -f %{buildroot}*/usr/include/codec2/codec2_fm.h
rm -f %{buildroot}*/usr/include/codec2/codec2_ofdm.h
rm -f %{buildroot}*/usr/include/codec2/comp.h
rm -f %{buildroot}*/usr/include/codec2/fmfsk.h
rm -f %{buildroot}*/usr/include/codec2/freedv_api.h
rm -f %{buildroot}*/usr/include/codec2/fsk.h
rm -f %{buildroot}*/usr/include/codec2/modem_stats.h
rm -f %{buildroot}*/usr/include/codec2/reliable_text.h
rm -f %{buildroot}*/usr/include/codec2/version.h
rm -f %{buildroot}*/usr/lib64/cmake/codec2/Codec2Config.cmake
rm -f %{buildroot}*/usr/lib64/cmake/codec2/Codec2Targets-relwithdebinfo.cmake
rm -f %{buildroot}*/usr/lib64/cmake/codec2/Codec2Targets.cmake
rm -f %{buildroot}*/usr/lib64/libcodec2.so
rm -f %{buildroot}*/usr/lib64/pkgconfig/codec2.pc
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/V4/usr/lib64/libcodec2.so.1.0
/usr/lib64/libcodec2.so.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-codec2-soname1/af54222a16839088fb1ffd5da88c1713472babc4
